### ISSUE TITLE
I've got passing code for UnusedTemp::when temp is used

### ISSUE THREAD

**Issue by bishboria** [mattwynne/raffle#3]
It's a simple example of the form

def thing
  fred = 35
  do_something_to fred
  42
end

I have made the code pass, and no other tests are breaking, but the solution simplistic.

Want me to commit?

**Comment by chrismdp** [comment]
Matt's started to use pull requests for any kind of discussion about code: its working well. Perhaps check it into a branch and make a pull request from it, so we can all have a look and talk about it?

## 

Chris Parsons
http://twitter.com/chrismdp
http://pa.rsons.org
(from my phone)

**Comment by bishboria** [comment]
Bugger, I've already committed and pushed... Didn't realise the pull request approach.

**Comment by chrismdp** [comment]
No worries mate :) just a suggestion.

## 

Chris Parsons
http://twitter.com/chrismdp
http://pa.rsons.org
(from my phone)

**Comment by mattwynne** [comment]
Yeah, next time the best thing to do is:
1. create a branch, commit a failing spec
2. push the branch
3. create pull request on GH from the head of the branch.

I don't think we should push things to master unless we're 100% certain it doesn't need any discussion.

**Comment by bishboria** [comment]
No problem! I'll make sure I do it next time.
